In [1]:
import numpy as np
import pandas as pd

In [2]:
api_usage=pd.read_excel("api_usage_5k_dirty_dataset.xlsx")

In [3]:
api_usage.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   usage_id             5000 non-null   int64
 1   user_id              4821 non-null   float64
 2   api_id               4797 non-null   float64
 3   usage_date           4944 non-null   str
 4   total_requests       4664 non-null   float64
 5   successful_requests  4644 non-null   float64
 6   failed_requests      4638 non-null   float64
dtypes: float64(5), int64(1), str(1)
memory usage: 273.6 KB

In [8]:
api_usage['user_id']=api_usage['user_id'].fillna(0)
api_usage['api_id']=api_usage['api_id'].fillna(0)

api_usage['user_id'].isnull().sum()
api_usage['api_id'].isnull().sum()

api_usage['user_id']=api_usage['user_id'].astype(int)
api_usage['api_id']=api_usage['api_id'].astype(int)

In [11]:
api_usage['usage_date']=pd.to_datetime(api_usage['usage_date'],format="mixed",errors='coerce')

api_usage['usage_date']=api_usage['usage_date'].fillna(api_usage['usage_date'].mode()[0])
api_usage['usage_date'].isnull().sum()

np.int64(0)

In [20]:
api_usage['total_requests']=api_usage['total_requests'].fillna(0)
api_usage['successful_requests']=api_usage['successful_requests'].fillna(0)
api_usage['failed_requests']=api_usage['failed_requests'].fillna(0)

api_usage['total_requests']=api_usage['total_requests'].astype(int)
api_usage['successful_requests']=api_usage['successful_requests'].astype(int)
api_usage['failed_requests']=api_usage['failed_requests'].astype(int)

In [21]:
api_usage.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   usage_id             5000 non-null   int64
 1   user_id              5000 non-null   int64
 2   api_id               5000 non-null   int64
 3   usage_date           5000 non-null   datetime64[us]
 4   total_requests       5000 non-null   int64
 5   successful_requests  5000 non-null   int64
 6   failed_requests      5000 non-null   int64
dtypes: datetime64[us](1), int64(6)
memory usage: 273.6 KB

In [22]:
api_usage.describe()

,usage_id,user_id,api_id,usage_date,total_requests,successful_requests,failed_requests
count,5000.000000,5000.00000,5000.000000,5000,5.000000e+03,5.000000e+03,5000.000000
mean,2500.500000,2767.61600,494.327800,2026-03-01 11:19:23.520000,6.051494e+05,5.930391e+05,12079.036400
min,1.000000,0.00000,0.000000,2026-01-01 00:00:00,0.000000e+00,-1.000000e+00,-5.000000
25%,1250.750000,1219.00000,55.750000,2026-02-01 00:00:00,4.170000e+02,2.657500e+02,8.000000
50%,2500.500000,2598.50000,123.000000,2026-02-28 00:00:00,1.781500e+03,1.678500e+03,38.000000
75%,3750.250000,3904.25000,194.000000,2026-04-01 00:00:00,3.492250e+03,3.397000e+03,108.000000
max,5000.000000,9998.00000,9997.000000,2026-12-01 00:00:00,2.493388e+07,2.472965e+07,497205.000000
std,1443.520003,2061.61616,1841.395434,NaN,3.191440e+06,3.136729e+06,63344.737014

In [25]:
api_usage['successful_requests'] = api_usage['successful_requests'].clip(lower=0)

api_usage['failed_requests'] = api_usage['failed_requests'].clip(lower=0)

In [26]:
api_usage['total_requests'] = (
    api_usage['successful_requests'] +
    api_usage['failed_requests']
)

In [27]:
api_usage.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   usage_id             5000 non-null   int64
 1   user_id              5000 non-null   int64
 2   api_id               5000 non-null   int64
 3   usage_date           5000 non-null   datetime64[us]
 4   total_requests       5000 non-null   int64
 5   successful_requests  5000 non-null   int64
 6   failed_requests      5000 non-null   int64
dtypes: datetime64[us](1), int64(6)
memory usage: 273.6 KB

In [28]:
api_usage.describe()

,usage_id,user_id,api_id,usage_date,total_requests,successful_requests,failed_requests
count,5000.000000,5000.00000,5000.000000,5000,5.000000e+03,5.000000e+03,5000.000000
mean,2500.500000,2767.61600,494.327800,2026-03-01 11:19:23.520000,6.051183e+05,5.930392e+05,12079.126400
min,1.000000,0.00000,0.000000,2026-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000
25%,1250.750000,1219.00000,55.750000,2026-02-01 00:00:00,3.797500e+02,2.657500e+02,8.000000
50%,2500.500000,2598.50000,123.000000,2026-02-28 00:00:00,1.740500e+03,1.678500e+03,38.000000
75%,3750.250000,3904.25000,194.000000,2026-04-01 00:00:00,3.492250e+03,3.397000e+03,108.000000
max,5000.000000,9998.00000,9997.000000,2026-12-01 00:00:00,2.493388e+07,2.472965e+07,497205.000000
std,1443.520003,2061.61616,1841.395434,NaN,3.191446e+06,3.136729e+06,63344.719845

In [33]:
api_usage[(api_usage['user_id'] == 0) | (api_usage['api_id'] == 0)]
api_usage = api_usage[
    (api_usage['user_id'] != 0) & (api_usage['api_id'] != 0)
]

In [37]:
api_usage.describe()

,usage_id,user_id,api_id,usage_date,total_requests,successful_requests,failed_requests
count,4710.000000,4710.000000,4710.000000,4710,4.710000e+03,4.710000e+03,4710.000000
mean,2493.040764,2713.915711,348.938429,2026-03-01 02:26:45.095541,6.423745e+05,6.295519e+05,12822.562420
min,1.000000,3.000000,1.000000,2026-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000
25%,1242.250000,1326.750000,62.000000,2026-01-31 00:00:00,5.542500e+02,4.685000e+02,10.000000
50%,2492.500000,2633.500000,127.000000,2026-02-28 00:00:00,1.935500e+03,1.884000e+03,43.000000
75%,3739.750000,3867.000000,193.000000,2026-03-31 00:00:00,3.584000e+03,3.495750e+03,113.000000
max,5000.000000,9998.000000,9997.000000,2026-12-01 00:00:00,2.493388e+07,2.472965e+07,497205.000000
std,1443.491761,1773.312226,1435.973236,NaN,3.284607e+06,3.228314e+06,65193.037561

In [42]:
api_usage[(api_usage['user_id'] == 0) | (api_usage['api_id'] == 0)]
api_usage.isnull().sum()
api_usage.duplicated().sum()


(api_usage['total_requests']==
    api_usage['successful_requests']+ api_usage['failed_requests']
).all()

api_usage['total_requests']=api_usage['successful_requests']+api_usage['failed_requests']

In [43]:
api_usage.describe()

,usage_id,user_id,api_id,usage_date,total_requests,successful_requests,failed_requests
count,4710.000000,4710.000000,4710.000000,4710,4.710000e+03,4.710000e+03,4710.000000
mean,2493.040764,2713.915711,348.938429,2026-03-01 02:26:45.095541,6.423745e+05,6.295519e+05,12822.562420
min,1.000000,3.000000,1.000000,2026-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000
25%,1242.250000,1326.750000,62.000000,2026-01-31 00:00:00,5.542500e+02,4.685000e+02,10.000000
50%,2492.500000,2633.500000,127.000000,2026-02-28 00:00:00,1.935500e+03,1.884000e+03,43.000000
75%,3739.750000,3867.000000,193.000000,2026-03-31 00:00:00,3.584000e+03,3.495750e+03,113.000000
max,5000.000000,9998.000000,9997.000000,2026-12-01 00:00:00,2.493388e+07,2.472965e+07,497205.000000
std,1443.491761,1773.312226,1435.973236,NaN,3.284607e+06,3.228314e+06,65193.037561

In [ ]:
api_usage['success_rate'] = (
  api_usage['successful_requests']/ api_usage['total_requests']) * 100

api_usage['success_rate'] = api_usage['success_rate'].fillna(0)

In [46]:
api_usage['error_rate'] = (
  api_usage['failed_requests']/ api_usage['total_requests']) * 100

api_usage['error_rate'] = api_usage['error_rate'].fillna(0)

In [47]:
api_usage.to_csv("cleaned_api_usage.csv",index=False)